<?php
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Headers: Content-Type");
header("Access-Control-Allow-Methods: GET, POST, OPTIONS");
header("Content-Type: application/json");

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    exit(0);
}

$diagramFile = __DIR__ . '/diagram.json';
$oalFile = __DIR__ . '/examples/generated.oal';

$action = $_GET['action'] ?? '';

switch ($action) {




    case 'compile':
        $input = json_decode(file_get_contents('php://input'), true);
        if (!$input) {
            http_response_code(400);
            echo json_encode(['error' => 'Invalid JSON input']);
            exit;
        }

        // 1. Save state and OAL first
        file_put_contents($diagramFile, json_encode($input, JSON_PRETTY_PRINT));
        $oalCode = $input['oal_code'] ?? '';
        if ($oalCode) {
            $examplesDir = __DIR__ . '/examples';
            if (!is_dir($examplesDir)) {
                mkdir($examplesDir, 0755, true);
            }
            file_put_contents($oalFile, $oalCode);
        } else {
            echo json_encode(['success' => false, 'output' => 'Error: OAL code is empty']);
            exit;
        }

        // 2. Change directory to project root and run compiler
        $projectRoot = __DIR__;
        $compilerScript = $projectRoot . '/generate.php';
        $relativeOalPath = 'examples/generated.oal';

        if (!file_exists($compilerScript)) {
            echo json_encode(['success' => false, 'output' => "Compiler generate.php not found at $compilerScript"]);
            exit;
        }

        // Execute compiler and capture stdout and stderr
        $currentDir = getcwd();
        chdir($projectRoot);
        
        $command = "php generate.php " . escapeshellarg($relativeOalPath) . " 2>&1";
        $output = [];
        $returnVar = 0;
        exec($command, $output, $returnVar);
        
        chdir($currentDir); // Restore directory

        $outputStr = implode("\n", $output);
        $success = ($returnVar === 0);
        $zipUrl = null;

        if ($success) {
            // Write PANDUAN.md to template/PANDUAN.md
            $panduanFile = $projectRoot . '/template/PANDUAN.md';
            $panduanContent = <<<EOD
# Panduan Penggunaan Laravel Project (Generated by OAL Editor)

Aplikasi Laravel ini telah berhasil di-generate secara otomatis menggunakan **OAL Editor**. Berikut adalah langkah-langkah panduan untuk melakukan instalasi, konfigurasi basis data, dan menjalankan aplikasi ini di lingkungan lokal Anda.

---

## 📋 Prasyarat Sistem
Sebelum memulai, pastikan sistem lokal Anda telah terinstal:
* **PHP 8.1** atau versi lebih baru.
* **Composer** (untuk manajemen dependensi PHP).
* Server database seperti **MySQL** atau **MariaDB** (bisa menggunakan XAMPP/MAMP).

---

## 🚀 Langkah-Langkah Instalasi

### 1. Instal Dependensi Project
Ekstrak berkas zip ini ke direktori kerja Anda. Buka terminal/command prompt di dalam folder hasil ekstrak tersebut, lalu jalankan perintah berikut untuk menginstal seluruh package Laravel yang dibutuhkan:
```bash
composer install
```

### 2. Salin Berkas Konfigurasi Lingkungan (`.env`)
Salin berkas `.env.example` menjadi `.env` dengan menjalankan perintah berikut di terminal:
```bash
cp .env.example .env
```
*(Di Windows, Anda dapat menduplikasi berkas `.env.example` secara manual dan mengganti namanya menjadi `.env`).*

### 3. Generate Application Key
Jalankan perintah berikut untuk membuat security key unik untuk aplikasi Laravel Anda:
```bash
php artisan key:generate
```

---

## 🗄️ Konfigurasi Database

1. **Buat Database Baru**:
   Buka phpMyAdmin (atau klien database pilihan Anda seperti DBeaver/Navicat), lalu buat database baru dengan nama pilihan Anda (misalnya: `oal_laravel_app`).

2. **Atur `.env`**:
   Buka berkas `.env` yang baru saja Anda buat menggunakan teks editor (VS Code, Notepad, dll.), lalu cari baris berikut dan sesuaikan dengan konfigurasi database Anda:
   ```env
   DB_CONNECTION=mysql
   DB_HOST=127.0.0.1
   DB_PORT=3306
   DB_DATABASE=oal_laravel_app
   DB_USERNAME=root
   DB_PASSWORD=
   ```
   *(Sesuaikan `DB_DATABASE`, `DB_USERNAME`, dan `DB_PASSWORD` sesuai server database lokal Anda).*

3. **Jalankan Migrasi Database (Membuat Struktur Tabel)**:
   Untuk membuat tabel database beserta seluruh kolom dan relasi kunci asing sesuai skema OAL Anda, jalankan perintah berikut:
   ```bash
   php artisan migrate
   ```

4. **Jalankan Seeder Database (Mengisi Data Uji Coba / Dummy - Opsional)**:
   Jika Anda ingin mengisi database dengan data dummy awal secara otomatis untuk keperluan uji coba API (sangat disarankan untuk local development), jalankan perintah berikut:
   ```bash
   php artisan db:seed
   ```
   *Atau, jika Anda ingin menjalankan migrasi ulang sekaligus seeding dalam satu perintah:*
   ```bash
   php artisan migrate:fresh --seed
   ```
   > ⚠️ **Catatan Penting**:
   > * DatabaseSeeder telah di-generate secara dinamis untuk mengisi data awal pada tabel independen maupun dependen secara aman guna menghindari kegagalan constraint.
   > * Hindari menjalankan seeder di server production agar database utama Anda tidak terisi oleh data dummy sampel.

---

## 💻 Menjalankan Server Lokal

Jalankan perintah artisan serve untuk menyalakan server lokal Laravel:
```bash
php artisan serve
```
Server lokal akan aktif, dan Anda dapat mengakses aplikasi di browser pada alamat:
👉 **[http://127.0.0.1:8000](http://127.0.0.1:8000)**

---

## 🛠️ Struktur Project yang Ter-generate
* **Models**: Berkas model Laravel terletak di `app/Models/*.php` beserta konfigurasi relasi (`hasMany`, `belongsTo`, dll.).
* **Migrations**: Struktur tabel terletak di `database/migrations/*.php`.
* **Controllers**: Logika pengolahan rute dan database terletak di `app/Http/Controllers/*.php`.
* **Middlewares**: Berkas middleware (seperti filter autentikasi) terletak di `app/Http/Middleware/*.php` dan terdaftar di `app/Http/Kernel.php`.
* **Routes**: Jalur rute web dan API terletak di `routes/web.php`.

---
*Generated automatically by OAL Editor - OAL Model & Laravel Generator.*
EOD;

            file_put_contents($panduanFile, $panduanContent);

            // Write postman_collection.json to template/postman_collection.json
            $postmanFile = $projectRoot . '/template/postman_collection.json';
            $postmanContent = generatePostmanCollection($input['routes'] ?? []);
            file_put_contents($postmanFile, $postmanContent);

            // Zip the template directory excluding vendor/node_modules/.git
            $zipDestination = $projectRoot . '/project_laravel.zip';
            if (file_exists($zipDestination)) {
                unlink($zipDestination);
            }
            if (zipDir($projectRoot . '/template', $zipDestination)) {
                $zipUrl = 'project_laravel.zip';
            }
        }

        // Clean up the temporary generated .oal file
        if (file_exists($oalFile)) {
            @unlink($oalFile);
        }

        echo json_encode([
            'success' => $success,
            'code' => $returnVar,
            'output' => $outputStr,
            'zip_url' => $zipUrl
        ]);
        break;

    default:
        http_response_code(404);
        echo json_encode(['error' => 'Action not found']);
        break;
}

function zipDir($source, $destination) {
    if (!extension_loaded('zip') || !file_exists($source)) {
        return false;
    }

    $zip = new ZipArchive();
    if (!$zip->open($destination, ZipArchive::CREATE | ZipArchive::OVERWRITE)) {
        return false;
    }

    $source = realpath($source);

    if (is_dir($source)) {
        $files = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($source, RecursiveDirectoryIterator::SKIP_DOTS),
            RecursiveIteratorIterator::SELF_FIRST
        );

        foreach ($files as $file) {
            $file = realpath($file);
            $relativePath = substr($file, strlen($source) + 1);

            // Exclude vendor, node_modules, and dot files
            if (strpos($relativePath, 'vendor') === 0 || 
                strpos($relativePath, 'node_modules') === 0 || 
                strpos($relativePath, '.git') === 0 ||
                $relativePath === '.phpunit.result.cache') {
                continue;
            }

            if (is_dir($file)) {
                $zip->addEmptyDir($relativePath);
            } else if (is_file($file)) {
                $zip->addFromString($relativePath, file_get_contents($file));
            }
        }
    } else if (is_file($source)) {
        $zip->addFromString(basename($source), file_get_contents($source));
    }

    return $zip->close();
}

function generatePostmanCollection($routes) {
    $items = [];
    foreach ($routes as $route) {
        $method = strtoupper($route['method'] ?? 'GET');
        $path = $route['path'] ?? '/';
        $cleanPath = ltrim($path, '/');
        
        $headers = [
            [
                'key' => 'Content-Type',
                'value' => 'application/json',
                'type' => 'text'
            ]
        ];

        // Autodetect authentication middlewares to pre-configure tokens
        $authMiddlewareActive = false;
        $mwList = $route['middlewares'] ?? [];
        foreach ($mwList as $mwName) {
            if (stripos($mwName, 'auth') !== false) {
                $authMiddlewareActive = true;
                break;
            }
        }

        if ($authMiddlewareActive) {
            $headers[] = [
                'key' => 'X-API-Key',
                'value' => 'secret123',
                'type' => 'text',
                'description' => 'Pre-configured API Auth Token'
            ];
            $headers[] = [
                'key' => 'token',
                'value' => '123456',
                'type' => 'text',
                'description' => 'Token preset for default AuthMiddleware'
            ];
        }

        // For POST/PUT, add a placeholder raw JSON body
        $body = null;
        if (in_array($method, ['POST', 'PUT', 'PATCH'])) {
            $body = [
                'mode' => 'raw',
                'raw' => "{\n    \"example_field\": \"example_value\"\n}",
                'options' => [
                    'raw' => [
                        'language' => 'json'
                    ]
                ]
            ];
        }

        // Parse path parts for Postman format
        $pathParts = explode('/', $cleanPath);

        $items[] = [
            'name' => "$method $path",
            'request' => array_filter([
                'method' => $method,
                'header' => $headers,
                'body' => $body,
                'url' => [
                    'raw' => '{{base_url}}/' . $cleanPath,
                    'host' => ['{{base_url}}'],
                    'path' => $pathParts
                ]
            ]),
            'response' => []
        ];
    }

    $collection = [
        'info' => [
            '_postman_id' => uniqid(),
            'name' => 'OAL Generated Laravel API',
            'description' => 'Collection generated automatically by OAL Editor for local endpoint testing.',
            'schema' => 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json'
        ],
        'item' => $items,
        'variable' => [
            [
                'key' => 'base_url',
                'value' => 'http://127.0.0.1:8000',
                'type' => 'string'
            ]
        ]
    ];

    return json_encode($collection, JSON_PRETTY_PRINT);
}
