<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthorController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\FineController;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\PublisherController;
use App\Http\Controllers\ReservationController;
use App\Http\Middleware\AuthMiddleware;

Route::get('/', [BookController::class, 'indexAction']);
Route::get('/books', [BookController::class, 'listBooksAction'])->middleware([AuthMiddleware::class]);
Route::get('/books/{id}', [BookController::class, 'showBookAction'])->middleware([AuthMiddleware::class]);
Route::post('/books', [BookController::class, 'createBookAction'])->middleware([AuthMiddleware::class]);
Route::put('/books/{id}', [BookController::class, 'updateBookAction'])->middleware([AuthMiddleware::class]);
Route::delete('/books/{id}', [BookController::class, 'deleteBookAction'])->middleware([AuthMiddleware::class]);
Route::post('/books/borrow', [BookController::class, 'borrowBookAction'])->middleware([AuthMiddleware::class]);
Route::post('/books/return', [BookController::class, 'returnBookAction'])->middleware([AuthMiddleware::class]);
Route::get('/categories', [CategoryController::class, 'listCategoriesAction']);
Route::get('/categories/{id}', [CategoryController::class, 'showCategoryAction']);
Route::post('/categories', [CategoryController::class, 'createCategoryAction']);
Route::put('/categories/{id}', [CategoryController::class, 'updateCategoryAction']);
Route::delete('/categories/{id}', [CategoryController::class, 'deleteCategoryAction']);
Route::get('/publishers', [PublisherController::class, 'listPublishersAction']);
Route::get('/publishers/{id}', [PublisherController::class, 'showPublisherAction']);
Route::post('/publishers', [PublisherController::class, 'createPublisherAction']);
Route::put('/publishers/{id}', [PublisherController::class, 'updatePublisherAction']);
Route::delete('/publishers/{id}', [PublisherController::class, 'deletePublisherAction']);
Route::get('/authors', [AuthorController::class, 'listAuthorsAction']);
Route::get('/authors/{id}', [AuthorController::class, 'showAuthorAction']);
Route::post('/authors', [AuthorController::class, 'createAuthorAction']);
Route::put('/authors/{id}', [AuthorController::class, 'updateAuthorAction']);
Route::delete('/authors/{id}', [AuthorController::class, 'deleteAuthorAction']);
Route::get('/members', [MemberController::class, 'listMembersAction']);
Route::get('/members/{id}', [MemberController::class, 'showMemberAction']);
Route::post('/members', [MemberController::class, 'registerMemberAction']);
Route::put('/members/{id}', [MemberController::class, 'updateMemberAction']);
Route::delete('/members/{id}', [MemberController::class, 'deleteMemberAction']);
Route::get('/reservations', [ReservationController::class, 'listReservationsAction'])->middleware([AuthMiddleware::class]);
Route::get('/reservations/{id}', [ReservationController::class, 'showReservationAction'])->middleware([AuthMiddleware::class]);
Route::post('/reservations', [ReservationController::class, 'reserveBookAction'])->middleware([AuthMiddleware::class]);
Route::delete('/reservations/{id}', [ReservationController::class, 'cancelReservationAction'])->middleware([AuthMiddleware::class]);
Route::get('/fines', [FineController::class, 'listFinesAction'])->middleware([AuthMiddleware::class]);
Route::get('/fines/{id}', [FineController::class, 'showFineAction'])->middleware([AuthMiddleware::class]);
Route::post('/fines/pay', [FineController::class, 'payFineAction'])->middleware([AuthMiddleware::class]);
