<?php

namespace Wahyurejeki\Oalcompiler\Express;

class ExpressControllerCompiler extends ExpressBaseCompiler
{
    private $controllers = [];
    private $usedModels = [];

    public function visitControllerStmt($ctx)
    {
        $name = $ctx->ID()->getText();
        $methods = [];

        $bodies = $ctx->controllerBody();
        if (!is_array($bodies)) $bodies = [$bodies];

        foreach ($bodies as $body) {
            $methods[] = $this->visit($body->controllerMethod());
        }

        $txtMethod = implode("\n\n", $methods);

        // Build JS Imports from OAL imports
        $importCode = "";
        foreach ($this->imports as $alias => $path) {
            $jsPath = (str_contains($path, '\\')) ? str_replace('\\', '/', $path) : $path;
            $importCode .= "const $alias = require('$jsPath');\n";
        }

        // Build local model imports
        $modelImports = "";
        if (!empty($this->usedModels[$name])) {
            foreach ($this->usedModels[$name] as $model) {
                $modelImports .= "const $model = require('../models/$model');\n";
            }
        }

        $controllerCode = <<<JS
// Generated by OAL Compiler for Express.js
$importCode
$modelImports
$txtMethod
JS;

        $this->controllers[$name] = $controllerCode;
        return $controllerCode;
    }

    public function visitControllerMethod($ctx)
    {
        $name = $ctx->CONTROLLER_METHOD_NAME()->getText();
        $params = ['req', 'res'];

        $bodyCode = $this->visit($ctx->block());

        return "exports.$name = async ($params[0], $params[1]) => $bodyCode";
    }

    private function getVariableName($ctx)
    {
        $parent = $ctx->getParent();
        while ($parent !== null) {
            $class = get_class($parent);
            if ($class === 'Context\VarStmtContext' || $class === 'Context\AssignmentStmtContext') {
                return $parent->ID()->getText();
            }
            $parent = $parent->getParent();
        }
        return null;
    }

    private function getCurrentControllerName($ctx)
    {
        $parent = $ctx->getParent();
        while ($parent !== null) {
            $class = get_class($parent);
            if ($class === 'Context\ControllerStmtContext') {
                return $parent->ID()->getText();
            }
            $parent = $parent->getParent();
        }
        return null;
    }

    public function visitModelMethodCall($ctx)
    {
        $controllerName = $this->getCurrentControllerName($ctx);
        $model = $ctx->ID()->getText();
        
        // Track used models for this controller
        $this->usedModels[$controllerName][$model] = $model;

        $method = $ctx->MODEL_METHOD()->getText();
        $paramsCtx = $ctx->modelMethodParams();
        $argsCode = [];

        if ($paramsCtx) {
            $tmp = $this->visit($paramsCtx);
            if (is_array($tmp)) $argsCode = $tmp;
        }

        $await = "await ";

        switch ($method) {
            case 'modelFindAll':
                $where = $this->buildSequelizeWhere($argsCode[0] ?? []);
                return "{$await}{$model}.findAll($where)";

            case 'modelFindOne':
                $where = $this->buildSequelizeWhere($argsCode[0] ?? []);
                return "{$await}{$model}.findOne($where)";

            case 'modelCreate':
                $data = $this->jsCode($argsCode[0] ?? []);
                return "{$await}{$model}.create($data)";

            case 'modelUpdate':
                $where = $this->buildSequelizeWhere($argsCode[0] ?? []);
                $updates = $this->jsCode($argsCode[1] ?? []);
                return "{$await}{$model}.update($updates, $where)";

            case 'modelDelete':
                $where = $this->buildSequelizeWhere($argsCode[0] ?? []);
                return "{$await}{$model}.destroy($where)";

            case 'modelCount':
                $where = $this->buildSequelizeWhere($argsCode[0] ?? []);
                return "{$await}{$model}.count($where)";

            default:
                return "// Unknown model method: $method";
        }
    }

    private function buildSequelizeWhere($args)
    {
        if (empty($args)) return "{}";
        
        $where = [];
        foreach ($args as $key => $value) {
            $key = trim($key, "\"'");
            if (is_array($value) && count($value) === 2) {
                $op = $value[0];
                $val = $this->jsCode($value[1]);
                $opMap = [
                    '==' => 'Op.eq',
                    '!=' => 'Op.ne',
                    '>' => 'Op.gt',
                    '>=' => 'Op.gte',
                    '<' => 'Op.lt',
                    '<=' => 'Op.lte',
                ];
                $jsOp = $opMap[$op] ?? $op;
                $where[] = "$key: { [$jsOp]: $val }";
            } else {
                $val = $this->jsCode($value);
                $where[] = "$key: $val";
            }
        }
        return "{ where: { " . implode(', ', $where) . " } }";
    }

    public function getControllers() { return $this->controllers; }
}
